### ISSUE TITLE
Resources occupied after client connections aborted

### ISSUE THREAD

**Issue by SingChia** [jeffallen/mqtt#10]
the server holds the resources of memories and threads while connections aborted by Ctrl+C, the resources release only happens while "incomingConn" reader or writer goroutine returned. is there a good way to notify server when connection closed?

**Comment by jeffallen** [comment]
The reader and writer loops on incominConn cleanup correctly if the TCP connection is broken (the read/write err is checked, return triggers defer and the read/write defers each cause the other loop to exit in a safe manner). But they both have "todos" for timeouts. Do you mean that resources are tied up by connections that are stalled, but not closed? In which case a pull req for timeouts would be welcome. Or do you mean some other failure case? In which case I need clear repro steps to know where to look.

**Comment by SingChia** [comment]
Sorry to interrupt you by my mistake, the reader loop  code was modified by others in my server, in io.EOF case, the "return" was modified to "continue". I should have checked the code before i start a new issue. and the mqttsrv does help me a lot, thanks for mqttsrv and your comment~

**Comment by jeffallen** [comment]
Could you please add a note to the wiki describing how you are using this? I wrote this as a toy, but I see that some people find it useful, and it would help me to know how, and for what, as I decide how to continue the project.

Closing this issue because you said you found the problem in your code, I think.
