### ISSUE TITLE
question about NAT

### ISSUE THREAD

**Issue by joeblew99** [jeffallen/mqtt#11]
I am playing with this MQTT lib, but now i am wondering how to connect to a remote device that is behind a NAted environment. At the remote location outbound connections over 80, 443 are allowed.
I might be able to get 22 outbound open too.

i basically are aiming for:
- being able to connect with SSH
- upgrade the software remotely. I plan to make the remote software just use 80 / 443. 

Any thoughts on best way to approach this ?

**Comment by jeffallen** [comment]
I have a suggestion, but it is currently covered by (someone else's) NDA. Please contact me in e-mail and I'll point you to it to investigate for yourself.

**Comment by joeblew99** [comment]
I sent you an email. Cheers
