### ISSUE TITLE
mqtt.go,  have a bug

### ISSUE THREAD

**Issue by cavin2kathy** [jeffallen/mqtt#13]
at line 586 : m.Header.QosLevel != proto.QosAtMostOnce
here may be  : m.Header.QosLevel != proto.QosAtLeastOnce

**Comment by jeffallen** [comment]
I will be traveling and can't look at this for a week. If it is urgent,
give more details on this issue and I'll see if I can give you a hint.

**Comment by jeffallen** [comment]
No.
