### ISSUE TITLE
Error: Invalid subscriptions - invalid qos

### ISSUE THREAD

**Issue by ssantosh21** [jeffallen/mqtt#14]
Hello Jeff,
I am getting above issue whenever I am trying to subscribe to any topic. Here are the steps which I followed:

1. Installation:
```
git clone https://github.com/aws/aws-iot-device-sdk-js.git
cd aws-iot-device-sdk-js
npm install
```

Sample code: 

```
var awsIot = require('aws-iot-device-sdk');
var device = awsIot.device({
   keyPath: './certs/private.pem.key',
  certPath: './certs/certificate.pem.crt',
    caPath: './certs/root-CA.crt',
  clientId: 'myThing',
    region: 'us-east-1'
});
```

```
  device
    .on('connect', function() {
      console.log('connected');
      device.subscribe('topic_1', function(error, result) {
        console.log(result);
      });
    });
```

it gets connected, however throws error on : 

```
device.subscribe('topic_1', function(error, result) {
        console.log(result);
```

Any guideline?

thanks,

**Comment by jeffallen** [comment]
You are asking about a client problem to the server author. Can you please
try the server with another client? If it works, try to find the difference
between the working client and yours using Wireshark. If that shows that
the server is sending something wrong, then come back and reopen this and
Welkom get you all fixed up.
