### ISSUE TITLE
 Authentication of Clients by the Server ？

### ISSUE THREAD

**Issue by eascode** [jeffallen/mqtt#20]
Authentication of Clients by the Server ？Where to verify, the test does not success。
pub/main.go and sub/main.go
var user = flag.String("user", "username", "username")
var pass = flag.String("pass", "12345", "password")
and
var user = flag.String("user", "", "username")
var pass = flag.String("pass", "", "password")

No difference was found

**Comment by jeffallen** [comment]
I'm sorry, I don't understand your question. Both pub and sub have "" as the second argument of flag.String because there it no default. If you are talking to an MQTT server that needs a user/pass, then you must use the -user and -pass options to set them.
