### ISSUE TITLE
Disconnect existing connections does  not work?

### ISSUE THREAD

**Issue by hzYanxp** [jeffallen/mqtt#21]
in mqtt.go

```
			// Disconnect existing connections.
			if existing := c.add(); existing != nil {
				disconnect := &proto.Disconnect{}
				r := existing.submitSync(disconnect)
				r.wait()
				existing.del()
			}
			c.add()
```

it seem  "Disconnect existing connections."does not work.

```
func (c *incomingConn) add() *incomingConn {
	clientsMu.Lock()
	defer clientsMu.Unlock()

	existing, ok := clients[c.clientid]
	if !ok {
		// this client id already exists, return it
		return existing
	}

	clients[c.clientid] = c
	return nil
}
```

to modify
	if !ok {   --- > if ok { 

in line 450:

```
// Delete a connection; the conection must be closed by the caller first.
func (c *incomingConn) del() {
	clientsMu.Lock()
	defer clientsMu.Unlock()
	delete(clients, c.clientid)
	return
}
```

How should I close the connection or the connection's goroutine ? thanks!

**Comment by jeffallen** [comment]
Please try the branch called issue21: https://github.com/jeffallen/mqtt/tree/issue21

If that solves your problem, tell me and I will check it in.

**Comment by hzYanxp** [comment]
I'm a new golang beginner,and learning the mqtt protocol.

"Disconnect existing connections" is ok. 

I think it's better the line 561# "c.replace()" is moved to the back of the line 560# "existing.del()".
 Both "replace()" and "add()" have "clients[c.clientid] = c".

**Comment by jeffallen** [comment]
I agree it was adding twice. Take a look at this and see if you agree with it:
  https://github.com/jeffallen/mqtt/pull/22/files
