### ISSUE TITLE
loadtest causes mqttsrv to try to use closed network connections

### ISSUE THREAD

**Issue by atilaneves** [jeffallen/mqtt#5]
With Go 1.5 on Arch Linux, running the server then loadtest with `--messages=500 --conns=500` never completes due to unreceived messages. The server prints:

    2015/10/15 15:51:14 {IncomingConn: 242846536268381992}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 {IncomingConn: 5207166632368852897}: failed to submit message
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46156: use of closed network connection
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46138: use of closed network connection
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46384: use of closed network connection
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46226: use of closed network connection
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46268: use of closed network connection
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46348: use of closed network connection
    2015/10/15 15:51:14 writer: write tcp [::1]:1883->[::1]:46442: use of closed network connection

**Comment by jeffallen** [comment]
Crazy, I can repro with only 2 concurrent connections. With loadtest and mqttsrv built with Go 1.5, I see this:

$ ./loadtest --messages=500 --conns=2
$ ./mqttsrv
2015/10/16 11:57:16 New client connected from 127.0.0.1:51462 as 6106767223293117013 (c1, k0).
2015/10/16 11:57:16 New client connected from 127.0.0.1:51463 as 6262886128805217406 (c1, k0).
2015/10/16 11:57:16 writer: write tcp 127.0.0.1:1883->127.0.0.1:51463: use of closed network connection

Recompile mqttsrv with Go 1.4.2 and the problem goes away. My testing is on MacOS, not Arch Linux, so it is a wider problem than just Linux.

Still diggin.

**Comment by jeffallen** [comment]
The error is coming from here:

		if err != nil {
			// This one is not interesting; it happens when clients
			// disappear before we send their acks.
			if err.Error() == "use of closed network connection" {
				return
			}
			log.Print("writer: ", err)
			return
		}

The format of the error string changed in Go 1.5, so the exception I'd added in the past no longer triggers. It is unclear how tha

It is also unclear who's fault this is w.r.t. the Go compatibility promise. Comparing errors to strings has heavy code smell, but I recall that this was the only way to do it, which means Go set me up to shoot my(future)self in the foot. Looking into it more.

But this place in the code doesn't really explain the hang problem either...

**Comment by jeffallen** [comment]
I have a fix for the "write one closed network connection" problem. But it's a cosmetic problem unrelated to the lost messages. Those are due to #2.

**Comment by jeffallen** [comment]
Fixed in 356d6046151.
