### ISSUE TITLE
mqttsrv can't handle loadtest

### ISSUE THREAD

**Issue by atilaneves** [jeffallen/mqtt#6]
`--conns=500 --messages=1000` causes it to do this:

015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub77}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub77}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub77}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: sub245}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message
2015/10/17 20:02:23 {IncomingConn: pub101}: failed to submit message

Fewer messages are fine.

**Comment by jeffallen** [comment]
This is a dup of #2. Which I'll work on but no eta.
